### ISSUE TITLE
LoadError on CI

### ISSUE THREAD

**Issue by mingxiangchan** [chrisalley/pundit-matchers#1]
I have an issue where the gem works perfectly fine on an existing db. However it will raise an error when running rake db:create/ rake db:drop, noticed it when it failed to pass CI.

rails_helper.rb
> ENV['RAILS_ENV'] ||= 'test'
> require File.expand_path('../../config/environment', __FILE__)
> require 'spec_helper'
> require 'rspec/rails'
> require 'clearance/rspec'
> require 'pundit/rspec'

spec_helper.rb
> require 'pundit/matchers'
> require 'capybara/rspec'

Logs:
> export RAILS_ENV="test"
> export RACK_ENV="test"
> bundle exec rake db:create db:schema:load --trace
> rake aborted!
> NoMethodError: undefined method `define' for RSpec::Matchers:Module
> /home/ubuntu/site/vendor/bundle/ruby/2.2.0/gems/pundit-matchers-1.0.0/lib/pundit/matchers.rb:3:in `<module:Matchers>'
> /home/ubuntu/site/vendor/bundle/ruby/2.2.0/gems/pundit-matchers-1.0.0/lib/pundit/matchers.rb:2:in `<module:Pundit>'
> /home/ubuntu/site/vendor/bundle/ruby/2.2.0/gems/pundit-matchers-1.0.0/lib/pundit/matchers.rb:1:in `<top (required)>'
> /home/ubuntu/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `require'
> /home/ubuntu/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:91:in `rescue in block in require'
> /home/ubuntu/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:68:in `block in require'
> /home/ubuntu/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
> /home/ubuntu/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
> /home/ubuntu/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
> /home/ubuntu/site/config/application.rb:17:in `<top (required)>'
> /home/ubuntu/site/Rakefile:4:in `require'
> /home/ubuntu/site/Rakefile:4:in `<top (required)>'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:75:in `run'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/bin/rake:33:in `<main>'
> LoadError: cannot load such file -- pundit-matchers
> /home/ubuntu/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
> /home/ubuntu/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
> /home/ubuntu/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
> /home/ubuntu/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
> /home/ubuntu/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
> /home/ubuntu/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
> /home/ubuntu/.rvm/gems/ruby-2.2.4@global/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
> /home/ubuntu/site/config/application.rb:17:in `<top (required)>'
> /home/ubuntu/site/Rakefile:4:in `require'
> /home/ubuntu/site/Rakefile:4:in `<top (required)>'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
> /home/ubuntu/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/rake/application.rb:75:in `run'>

> export RAILS_ENV="test"
> export RACK_ENV="test"
> bundle exec rake db:create db:schema:load --trace
>  returned exit code 1>

> /home/ubuntu/.rvm/rubies/ruby-2.2.4/bin/rake:33:in `<main>' Action failed: rake db:create db:schema:load

**Comment by chrisalley** [comment]
I was unable to reproduce the error. Can you please create a fresh Rails app with the minimal codebase required to reproduce the error? We can then rule out other factors. I would be happy to take a look at the source code of the app once you've done this.

**Comment by mingxiangchan** [comment]
apologies on the late reply as I was quite busy. The requested test repo is below:
https://github.com/mingxiangchan/test_pundit_matchers

The error shows up on the repo when trying to run $ rake db:create
> uninitialized constant RSpec::Matchers (NameError)

It also occured when running $ rails g rspec:install, had to remove the gem from gemfile to allow the rspec:install command to run

**Comment by chrisalley** [comment]
It appears that Rails was trying to load the matchers in development while running `rake db:create` and `rails g spec:install`, but couldn't. Since pundit-matchers is not required in development, in your Gemfile, I moved the gem out of the `group :development, :test` block into a new block exclusively for the test environment:

```
group :test do
  gem 'pundit-matchers', '~> 1.0.0'
end
```

I've updated the Readme to mention this requirement.

**Comment by danielmackey** [comment]
For anyone else who encounters this, I got around it by adding a `require: false` to

```rb
group :test do
  gem 'pundit-matchers', '~> 1.0.0', require: false
end
```

It appears that most CI's will do something like 
```
RAILS_ENV=test RACK_ENV=test bundle exec rake db:create db:schema:load
```

This loading of the `test` environment loads the pundit-matcher library, but hasn't required rspec yet, thus throwing the error that @mingxiangchan and I encountered. 

Additionally, I'm submitting a pull request to `require 'rspec/core'` in the matchers class which should address this as well.
