### ISSUE TITLE
Fails when model is not "user"

### ISSUE THREAD

**Issue by seanfcarroll** [chrisalley/pundit-matchers#10]
Hi Chris,

A great little gem, excellent work. I am using it in our Machine Learning challenge platform [crowdAI](www.crowdai.org). In this application, we use a **Participant** model rather than the default **User** model.

This works, but I was wondering how to contribute are more general solution that would allow changing of the user model name. Would you consider an initializer?

I noticed when a test fails in Rspec, the matcher message dies, because user is referenced in the code. For now, I've [forked](https://github.com/crowdAI/pundit-matchers/commit/309eae16c88e61c0c2cad09c43c7eb0164a93f33) the code and replaced user with participant, but I'd be happy to contribute a PR with a more flexible solution and relevant tests.

**Default - with user**

```ruby
Failures:

  1) ArticlePolicy for a published article for the author should forbid action :destroy
     Failure/Error: it { is_expected.to forbid_action(:destroy) }

     NoMethodError:
       undefined method `user' for #<ArticlePolicy:0x007ffb0c1ffea0>
     # ./spec/policies/article_policy_spec.rb:31:in `block (4 levels) in <top (required)>'
```

**Corrected for participant- with the fork**

```ruby
  1) ArticlePolicy for a published article for the author should forbid action :destroy
     Failure/Error: it { is_expected.to forbid_action(:destroy) }
       ArticlePolicy does not forbid destroy on #<Article:0x007fee05fccfb0> for #<Participant id: 2413, email: "darcy@dubuquekiehn.us", admin: false, verified: false, verification_date: nil, timezone: nil, created_at: "2017-05-26 11:10:18", updated_at: "2017-05-26 11:10:18", organizer_id: nil, name: "name_20", email_public: false, bio: nil, website: nil, github: nil, linkedin: nil, twitter: nil, account_disabled: false, account_disabled_reason: nil, account_disabled_dttm: nil, slug: "name_20", api_key: "c18594859ac45c223ad43d8e86387787", location: nil, image_file: nil>.
     # ./spec/policies/article_policy_spec.rb:31:in `block (4 levels) in <top (required)>'
```

**Comment by chrisalley** [comment]
The same issue occurs when `record` is not used (see #4). We might be able to come up with a general solution for both cases here.

A simple solution would be check to see whether `user` is defined (e.g.`if defined? policy.user`) and only then include the details of the user in the failure message. This would cover most cases where `user` is used. If we want to output the details of `participant` and other variations, it's going to be trickier to find a clean solution. If we went with an initialiser approach, what would that look like in the specs?

**Comment by seanfcarroll** [comment]
I'll take a look at the code ... I wonder if there is a way to introspect and find whatever model is the 'user' model. Actually if we can avoid using an initializer, I think that's best. Let me look into it.

**Comment by chrisalley** [comment]
The user alias is now configurable. See PR #17 and the readme for more details.
