### ISSUE TITLE
permit_actions/forbid_actions doesn't accept single item array

### ISSUE THREAD

**Issue by wesley-harding** [chrisalley/pundit-matchers#14]
Is there a reason that the permit_actions and forbid_actions refuse an array of a single item? 

I understand their is the singular case for each which accepts a value directly. However, it seems unnecessary to throw a validation error for a single item array. As long as they provided value is an array and is not empty, it seems like it should be accepted.

I'd like to see this validation taken out as I find it pointless to need to switch the method name when transitioning from a single to multiple (and vice versa) actions. It'd be great to simply use the plural method in all cases so I can easily add/remove arguments.

I'll happily get a PR in for a change. I wanted to make sure I understood the reasoning behind the current implementation before I went to change it.

Thanks!

**Comment by chrisalley** [comment]
It was done this way with the aim of making it easier for the reader to translate line into English in their head.

"The article policy is expected to permit the action: create" and "The article policy is expected to permit the actions: create and update" sound natural.
"The article policy is expected to permit the actions: create" sounds less natural.

Admittedly, this is a small problem for the reader, but it does help a little I think. Programmers often spend more time reading code than writing it. That being said, if you're still unconvinced, feel free to send a PR removing the restriction.

**Comment by wesley-harding** [comment]
I think having both options makes a lot of sense from a readability perspective. It just seems unnecessary to enforce singularity on the plural action. 

I'll look to submit a PR in the next couple of days.

**Comment by chrisalley** [comment]
PR merged and released as part of Pundit Matchers 1.4.0.

**Comment by wesley-harding** [comment]
Wonderful!  Thank you very much!

**Comment by wesley-harding** [comment]
I'll need to revisit this. It looks like merge of #13 had some conflicts that break this newly introduced functionality.

When a single item array is provided to a plural matcher, the matcher always fails. The singular version works as expected.

**Comment by chrisalley** [comment]
I see what happened there. The tests should have failed as well, but because of the JRuby Travis issue we didn't pick up on that. This is all fixed in version 1.4.1.

**Comment by wesley-harding** [comment]
Sweet, thanks for taking care of that so quickly!
