### ISSUE TITLE
Support for array of attributes in permit/forbid_mass_assignment_of

### ISSUE THREAD

**Issue by stephendolan** [chrisalley/pundit-matchers#20]
What are the group's thoughts on making the same change to `permit/forbid_mass_assignment_of` as the one that was made in #8?

It would be great to get rid of some of the duplication and manual workarounds for models with lots of permitted attributes.

**Comment by chrisalley** [comment]
It's a good suggestion. We should require that an array is passed to the matcher when testing multiple attributes (for consistency with `permit_action` and `permit_actions`).

There is a related discussion in #7 for adding nested attributes.

**Comment by chrisalley** [comment]
Merged and released as version 1.6.0. Thanks! I thought up some potential improvements which I've added to the issues list; feel free to have a look at them and offer feedback if you're interested.
