### ISSUE TITLE
Undefined method 'define'

### ISSUE THREAD

**Issue by ivane-gkomarteli** [chrisalley/pundit-matchers#28]
I am getting the following error when including the gem.

**pundit-matchers-1.6.0/lib/pundit/matchers.rb:23:in `<module:Matchers>': undefined method `define' for RSpec::Matchers:Module**

I am using:

Rails - 5.0
pundit -  2.0.0
rspec-rails - 3.7.1

Could this be a version issue?

**Comment by vcharap** [comment]
You most likely need to add `require: false` to the gem declaration

```ruby
gem 'pundit-matchers', '~> 1.6.0', require: false
```

See #1

**Comment by chrisalley** [comment]
Thanks to @vcharap for responding. If this is still an issue, please open a new issue. Closing.
